/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function DonutGLTF(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/new-donut-for-threejs.gltf"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
    
      <group name="Scene">
        <mesh
          name="Donut"
          castShadow
          receiveShadow
          geometry={nodes.Donut.geometry}
          material={materials["Material.003"]}
          position={[0, 0, 0.01]}
          rotation={[1.11, 0.25, -0.46]}
        >
          <group name="Icing">
            <mesh
              name="Torus003"
              castShadow
              receiveShadow
              geometry={nodes.Torus003.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Torus003_1"
              castShadow
              receiveShadow
              geometry={nodes.Torus003_1.geometry}
              material={materials.Sprinkle}
            />
          </group>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/new-donut-for-threejs.gltf");
