/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'


export default function DonutGLTF(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/new-donut-for-threejs.gltf"
  );
  const { actions } = useAnimations(animations, group);
  const [animationState, setAnimation] = useState(false);

  useFrame(({ mouse, viewport }) => {
    if(!animationState) {
      const x = (mouse.x * viewport.width) / 2.5
      const y = (mouse.y * viewport.height) / 2.5
      group.current.lookAt(x, y, 1)
    }
  })

  const handleClick = () => {
    if(!animationState) {
      setAnimation(true);
      actions.DonutAction.setEffectiveTimeScale(1)
      actions.DonutAction.play();
    } else {
      setAnimation(false);
      actions.DonutAction.setEffectiveTimeScale(0)
    }
  }

  return (
    <group ref={group} {...props} dispose={null} onClick={handleClick}>
    
      <group name="Scene">
        <mesh
          name="Donut"
          castShadow
          receiveShadow
          geometry={nodes.Donut.geometry}
          material={materials["Material.003"]}
          position={[0, 0, 0.01]}
          rotation={[1.11, 0.25, -0.46]}
        >
          <group name="Icing">
            <mesh
              name="Torus003"
              castShadow
              receiveShadow
              geometry={nodes.Torus003.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Torus003_1"
              castShadow
              receiveShadow
              geometry={nodes.Torus003_1.geometry}
              material={materials.Sprinkle}
            />
          </group>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/new-donut-for-threejs.gltf");
