/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 remodel-knobs.glb --transform --keepmeshes 
Files: remodel-knobs.glb [18MB] > /Users/rouven/Dev/projects/private/websites/devsite/public/model/remodel-knobs-transformed.glb [1.06MB] (94%)
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations, MeshPortalMaterial } from "@react-three/drei";
import { useResponsiveCamera } from "@/src/hooks/useResponsiveCamera";
import { useCameraState } from "@/src/state/camera";
import { useShallow } from "zustand/react/shallow";
import useExplore from "@/src/hooks/useExplore";
import * as THREE from "three";
import { ProjectPortals } from "./ProjectPortals";

export function CameraNewTransformed({ cameraRef, ...props }) {
  const group = useRef();
  const portalMeshRef = useRef();
  const portalMaterialRef = useRef();
  const [isPortalActive, setIsPortalActive] = useState(false);
  const { nodes, materials, animations } = useGLTF(
    "/model/remodel-knobs-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useResponsiveCamera();

  const { scale, position, rotation } = useCameraState(
    useShallow((state) => ({
      scale: state.scale,
      position: state.position,
      rotation: state.rotation,
    }))
  );

  useExplore(group, {
    target: "position",
    exploringProps: {
      x: 0.4,
      z: 2.2,
      y: -0.6,
    },
    notExploringProps: {
      x: 1,
      y: -0.4,
      z: 0,
    },
  });

  useExplore(group, {
    target: "rotation",
    exploringProps: {
      y: -Math.PI / 2,
    },
    notExploringProps: {
      y: Math.PI / 2,
    },
  });

  return (
    <group
      ref={(el) => {
        group.current = el;
        if (cameraRef) cameraRef.current = el;
      }}
      {...props}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      <group name="Scene">
        <group name="Cam" position={[-0.002, 0.001, 0]}>
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane001_2"
            geometry={nodes.Plane001_2.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane001_3"
            geometry={nodes.Plane001_3.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane001_4"
            geometry={nodes.Plane001_4.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group name="Display001" position={[0.006, 0.002, 0]}>
          <mesh
            name="Plane004"
            geometry={nodes.Plane004.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            ref={portalMeshRef}
            name="Plane004_1"
            geometry={nodes.Plane004_1.geometry}
            material={materials.PaletteMaterial001}
          >
            <MeshPortalMaterial
              ref={portalMaterialRef}
              blend={0}
              colorFormat={THREE.RGBAFormat}
              toneMapped={false}
              transparent
              depthWrite={false}
              side={THREE.DoubleSide}
            >
              <color attach="background" args={[1, 1, 1]} />
              <ProjectPortals />
            </MeshPortalMaterial>
          </mesh>
        </group>
        <mesh
          name="Circle002"
          geometry={nodes.Circle002.geometry}
          material={materials.PaletteMaterial001}
          position={[0.014, 0.107, 0.082]}
          rotation={[0.078, 0.061, -1.341]}
        />
        <mesh
          name="Circle001"
          geometry={nodes.Circle001.geometry}
          material={materials.PaletteMaterial001}
          position={[0.014, 0.107, -0.025]}
          rotation={[0.078, 0.061, -1.341]}
        />
        <mesh
          name="Circle003"
          geometry={nodes.Circle003.geometry}
          material={materials.PaletteMaterial001}
          position={[0.014, 0.106, -0.081]}
          rotation={[0.078, 0.061, -1.341]}
        />
        <mesh
          name="Circle004"
          geometry={nodes.Circle004.geometry}
          material={materials.PaletteMaterial001}
          position={[0.016, 0.065, -0.047]}
          rotation={[0.085, -0.001, -Math.PI / 2]}
        />
        <mesh
          name="Circle005"
          geometry={nodes.Circle005.geometry}
          material={materials.PaletteMaterial001}
          position={[0.014, 0.107, 0.067]}
          rotation={[0.078, 0.061, -1.341]}
        />
        <mesh
          name="Circle006"
          geometry={nodes.Circle006.geometry}
          material={nodes.Circle006.material}
          position={[-0.044, 0.109, -0.077]}
          rotation={[-0.026, 0.126, 0.23]}
        />
        <mesh
          name="Circle007"
          geometry={nodes.Circle007.geometry}
          material={nodes.Circle007.material}
          position={[-0.017, 0.116, -0.086]}
          rotation={[0.003, 0.167, 0]}
        />
        <mesh
          name="Circle008"
          geometry={nodes.Circle008.geometry}
          material={nodes.Circle008.material}
          position={[-0.017, 0.116, -0.068]}
          rotation={[-0.026, 0.186, 0.019]}
        />
        <mesh
          name="Circle009"
          geometry={nodes.Circle009.geometry}
          material={materials.PaletteMaterial001}
          position={[0.016, 0.013, -0.046]}
          rotation={[0.085, -0.001, -Math.PI / 2]}
        />
        <mesh
          name="Circle010"
          geometry={nodes.Circle010.geometry}
          material={materials.PaletteMaterial001}
          position={[0.016, 0.013, -0.065]}
          rotation={[0.085, -0.001, -Math.PI / 2]}
        />
        <mesh
          name="IsoButton"
          geometry={nodes.IsoButton.geometry}
          material={materials.PaletteMaterial001}
          position={[0.014, 0.038, -0.055]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Detail"
          geometry={nodes.Detail.geometry}
          material={materials.PaletteMaterial001}
          position={[0.018, 0.059, -0.052]}
        />
        <mesh
          name="Idk"
          geometry={nodes.Idk.geometry}
          material={materials.PaletteMaterial001}
          position={[0, 0.116, -0.061]}
          scale={1.193}
        />
        <mesh
          name="Knob"
          geometry={nodes.Knob.geometry}
          material={materials.PaletteMaterial001}
          position={[0.001, 0.119, -0.087]}
        />
        <mesh
          name="ModeKnob"
          geometry={nodes.ModeKnob.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.009, 0.125, -0.033]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/remodel-knobs-transformed.glb");
