/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/cam-final-smooth1.glb --transform -j 
Files: public/cam-final-smooth1.glb [5.33MB] > /Users/rouven/Dev/projects/private/websites/devsite/cam-final-smooth1-transformed.glb [1.81MB] (66%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CameraNew(props) {
    const { nodes, materials } = useGLTF("/cam-final-smooth1-transformed.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cam.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.Iso_Button.geometry}
                material={materials.PaletteMaterial002}
            />
            <mesh
                geometry={nodes.Button.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_2.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_3.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Mode_Button.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_4.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_5.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_6.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_7.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.Button_8.geometry}
                material={materials.PaletteMaterial002}
            />
            <mesh
                geometry={nodes.Sensor.geometry}
                material={materials.PaletteMaterial004}
            />
            <mesh
                geometry={nodes.Display.geometry}
                material={materials.PaletteMaterial002}
            />
            <mesh
                geometry={nodes.Display_Frame.geometry}
                material={materials.PaletteMaterial003}
            />
            <mesh
                geometry={nodes.sensor_circle.geometry}
                material={materials.PaletteMaterial002}
            />
            <mesh
                geometry={nodes.Sensor_Circle.geometry}
                material={materials["Die-cast aluminum"]}
            />
            <mesh
                geometry={nodes.Sensor_Inner_Circle.geometry}
                material={materials["Die-cast aluminum"]}
            />
            <mesh
                geometry={nodes.Sensor_Frame.geometry}
                material={materials["Die-cast aluminum"]}
            />
            <mesh
                geometry={nodes.Camera_Handle_Missing.geometry}
                material={materials["Rubber Matt"]}
            />
            <mesh
                geometry={nodes.Viewfinder.geometry}
                material={materials.PaletteMaterial005}
            />
        </group>
    );
}

useGLTF.preload("/cam-final-smooth1-transformed.glb");
